package ClientServer;

public enum InquiryManagerActions {
    ALL_INQUIRY,
    ADD_INQUIRY,
    TEST,
    RETURN_REPRESENTATIVE_BY_INQUIRYID,
    GET_ALL_REPRESENTATIVES,
    RETURN_INQUIRY_STATUS,
    RETURN_INQUIRIES_IN_MONTH,
    CANCEL_INQUIRY
}
